cyber/cyber/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cyberapp.urls')),
    path('', include('rag.urls')),
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin/', admin.site.urls),
]

cyber/cyberapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'cyberapp'
urlpatterns = [
                  path('signup/', views.user_signup, name='signup'),
                  path('login/', views.user_login, name='login'),
                  path('change_password/', views.change_password, name='change_password'),
                  path('forgot_password/', views.forget_password, name='forgot_password'),
                  path('success/', views.success, name='success'),
                  path('home/', views.home, name='home_user'),
                  path('users_chart/', views.logged_in_users_chart, name='users_chart_login'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cyber/rag/urls.py
# rag/urls


from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
                  path('', views.home, name='home'),
                  path('chat/', views.chatbot_response, name='chat'),
                  path('staffs/', views.staff_chatbot, name='staffs'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

cyber/cyberapp/models.py
from django.contrib.auth.models import User
from django.db import models


# # Create your models here.
# class Document(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     pdf = models.FileField(upload_to='pdfs/')
#     uploaded_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"{self.user.username}'s PDF"

cyber/cyberapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# from .models import Document


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput)
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('Incorrect old password.')
        return old_password

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("New passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        new_password = self.cleaned_data['new_password1']
        self.user.set_password(new_password)
        if commit:
            self.user.save()
        return self.user


# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Document
#         fields = ['pdf']
#         required = ['pdf']
#         readonly_fields = ['uploaded_at']

cyber/cyberapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from .forms import SignupForm, LoginForm, ChangePasswordForm


# Create your views here.

def home(request):
    return render(request, 'home.html')


# login page
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('cyberapp:home_user')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


# signup page
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cyberapp:login')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('cyberapp:success')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })


def success(request):
    return render(request, 'success.html')


def forget_password(request):
    return render(request, 'forgot_password.html')


# logout page
def user_logout(request):
    logout(request)
    return redirect('login')


# @login_required
# def upload_file(request):
#     if request.method == 'POST':
#         form = DocumentForm(request.POST, request.FILES)
#         if form.is_valid():
#             document = form.save(commit=False)
#             document.user = request.user
#             document.save()
#             messages.success(request, "PDF Uploaded")
#         else:
#             return render(request, 'upload_document.html', {'form': form})
#     else:
#         form = DocumentForm()
#     return render(request, 'upload_document.html', {'form': form})


def logged_in_users_chart(request):
    # Retrieve data for logged-in users
    logged_in_users = User.objects.filter(is_active=True)
    staff_users = User.objects.filter(is_staff=True)
    user_count = logged_in_users.count()
    staff_count = staff_users.count()
    user_data = {
        'logged_in_users': user_count,
        'staff_users': staff_count,
    }
    return render(request, 'chart.html', {'user_data': user_data})

cyber/cyberapp/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .bg-white {
            padding: 20px;
        }

        h3 {
            font-size: 1.5rem;
        }

        .form-label {
            font-size: 0.9rem;

            .form-control {
                font-size: 0.9rem;
                padding: 8px 12px;
            }

            .btn-primary {
                font-size: 0.9rem;
                padding: 10px 20px;
            }
        }
    </style>
</head>
<body>
<div class="bg-light py-3 py-md-5">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="text-center alert alert-success mb-3">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-11 col-lg-8 col-xl-5 col-xxl-6">
                <div class="bg-white p-4 p-md-5 rounded shadow-sm">
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <h3>Change Password</h3>
                            </div>
                        </div>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <div class="row gy-3 gy-md-4 overflow-hidden">
                                    <div class="col-12">
                                        <label for="{{ field.id_for_label }}"
                                               class="form-label">{{ field.label }}</label>
                                        {{ field }}
                                        {% if field.errors %}
                                            <div class="invalid-feedback">
                                                {% for error in field.errors %}
                                                    {{ error }}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-12">
                            <div class="d-grid">
                                <button class="btn btn-primary"
                                        style="background-color: #033e8c; border: none; font-size: 18px;"
                                        type="submit">Change Password
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

cyber/cyberapp/templates/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged-in Employees Stat</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
<div>
    <div class="container">
        <div class="user-count">
            <p>Employees Count: {{ user_data.logged_in_users }}</p>
        </div>
        <div class="staff-count">
            <p>Staff Count : {{ user_data.staff_users }}</p>
        </div>
    </div>
    <div class="row">
        <div class="chart-container">
            <canvas id="myBarChart"></canvas>
        </div>
        <div class="chart-container">
            <canvas id="myPieChart"></canvas>
        </div>
    </div>

</div>

<style>
    .user-count {
        display: inline-flex;
        flex-direction: column;
        background-color: #d1e7dd;
        border: 1px solid #badbcc;
        border-radius: 10px;
        width: 20%;
        text-align: center;
        font-family: 'Poppins', 'Arial', sans-serif;
        font-size: 16px;
        cursor: pointer;
    }

    .staff-count {
        display: inline-flex;
        flex-direction: column;
        background-color: #d1e7dd;
        border: 1px solid #badbcc;
        border-radius: 10px;
        width: 20%;
        text-align: center;
        font-family: 'Poppins', 'Arial', sans-serif;
        font-size: 16px;
        cursor: pointer;
    }

    .container {
        position: relative;
        display: flex;
        justify-content: center;
        gap: 20px;
        padding-top: 20px;
    }

    .row {
        display: flex;
        flex-direction: row;
        justify-content: center;
        padding-top: 50px;
    }
</style>

<script>
    const ctx = document.getElementById('myBarChart').getContext('2d');
    const pieCtx = document.getElementById('myPieChart').getContext('2d');
    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Employees', 'Staff'],
            datasets: [{
                label: 'Count Employees',
                data: [{{ user_data.logged_in_users }}, {{ user_data.staff_users }}],
                backgroundColor: 'rgba(255, 99, 132, 0.2)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            },
            layout: {
                padding: {
                    left: 10, // Reduced left padding
                    right: 10, // Reduced right padding
                    top: 10, // Reduced top padding
                    bottom: 10 // Reduced bottom padding
                }
            },
            responsive: true,
            maintainAspectRatio: false,
            aspectRatio: 1 // Set aspect ratio to adjust width and height
        }
    });

    new Chart(pieCtx, {
        type: 'pie',
        data: {
            labels: ['Total Employees', 'Staff'],
            datasets: [{
                label: 'Count Employees',
                data: [{{ user_data.logged_in_users }}, {{ user_data.staff_users }}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            layout: {
                padding: {
                    left: 100, // Reduced left padding
                    right: 10, // Reduced right padding
                    top: 10, // Reduced top padding
                    bottom: 10 // Reduced bottom padding
                }
            },
            responsive: true,
            maintainAspectRatio: false,
            aspectRatio: 1 // Set aspect ratio to adjust width and height
        }
    });

</script>
</body>
</html>

cyber/cyberapp/templates/forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forget Password</title>
</head>
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .bg-white {
            padding: 20px;
        }

        h3 {
            font-size: 1.5rem;
        }

        .form-label {
            font-size: 0.9rem;

            .form-control {
                font-size: 0.9rem;
                padding: 8px 12px;
            }

            .btn-primary {
                font-size: 0.9rem;
                padding: 10px 20px;
            }
        }
    </style>
</head>
<body>
<div class="bg-light py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-11 col-lg-8 col-xl-5 col-xxl-6">
                <div class="bg-white p-4 p-md-5 rounded shadow-sm">
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <h3>Reset Password</h3>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'cyberapp:forget_password' %}" method="POST">
                        {% csrf_token %}
                        <div class="row gy-3 gy-md-4 overflow-hidden">
                            <div class="col-12">
                                <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control" name="email" id="email"
                                       placeholder="name@example.com" value="" required>
                            </div>
                            <div class="col-12">
                                <div class="d-grid">
                                    <button class="btn btn-primary"
                                            style="background-color: #033e8c; border: none; font-size: 18px;"
                                            type="submit">Reset Password
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

</body>
</html>

cyber/cyberapp/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .bg-white {
            padding: 20px;
        }

        h3 {
            font-size: 1.5rem;
        }

        .form-label {
            font-size: 0.9rem;

            .form-control {
                font-size: 0.9rem;
                padding: 8px 12px;
            }

            .btn-primary {
                font-size: 0.9rem;
                padding: 10px 20px;
            }
        }
    </style>
</head>
<body>
<div class="bg-light py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-11 col-lg-8 col-xl-5 col-xxl-4">
                <div class="bg-white p-4 p-md-5 rounded shadow-sm">
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <h3>Reset Password</h3>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'cyberapp:change_password' %}" method="POST">
                        {% csrf_token %}
                        <div class="row gy-3 gy-md-4 overflow-hidden">
                            <div class="col-12">
                                <label for="email" class="form-label">Email<span
                                        class="text-danger">*</span></label>
                                <input type="email" class="form-control" name="email" id="email"
                                       placeholder="name@example.com" required>
                            </div>
                            <div class="col-12">
                                <div class="d-grid">
                                    <button class="btn btn-primary"
                                            style="background-color: #033e8c; border: none; font-size: 18px;"
                                            type="submit">Reset Password
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

cyber/cyberapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
 <h1>Home</h1>
</body>
</html>

cyber/cyberapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .bg-white {
            padding: 20px;
        }

        h3 {
            font-size: 1.5rem;
        }

        .form-label {
            font-size: 0.9rem;

            .form-control {
                font-size: 0.9rem;
                padding: 8px 12px;
            }

            .btn-primary {
                font-size: 0.9rem;
                padding: 10px 20px;
            }
        }
    </style>
</head>
<body>
<!-- Login  - Bootstrap Brain Component -->
<div class="bg-light py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-11 col-lg-8 col-xl-5 col-xxl-4">
                <div class="bg-white p-4 p-md-5 rounded shadow-sm">
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <h3>Log in</h3>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'cyberapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="row gy-3 gy-md-4 overflow-hidden">
                            <div class="col-12">
                                <label for="username" class="form-label">Username<span
                                        class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username" id="username"
                                       placeholder="name@example.com" required>
                            </div>
                            <div class="col-12">
                                <label for="password" class="form-label">Password <span
                                        class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password" id="password"
                                       required>
                            </div>
                            <div class="col-12">
                                <div class="d-grid">
                                    <button class="btn btn-primary"
                                            style="background-color: #033e8c; border: none; font-size: 18px;"
                                            type="submit">Log in
                                    </button>
                                </div>
                            </div>
                             {% if messages %}
                                    {% for message in messages %}
                                        <div class="text-center alert alert-success mb-3">{{ message }}</div>
                                    {% endfor %}
                                {% endif %}
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-12">
                            <hr class="mt-4 mb-3 border-secondary-subtle">
                            <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end">
                                <a href="{% url 'cyberapp:signup' %}" class="link-secondary text-decoration-none">Create
                                    new
                                    account</a>
                                <a href="{% url 'cyberapp:forgot_password' %}"
                                   class="link-secondary text-decoration-none">Forgot password</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

cyber/cyberapp/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .bg-white {
            padding: 20px;
        }

        h3 {
            font-size: 1.5rem;
        }

        .form-label {
            font-size: 0.9rem;

            .form-control {
                font-size: 0.9rem;
                padding: 8px 12px;
            }

            .btn-primary {
                font-size: 0.9rem;
                padding: 10px 20px;
            }
        }
    </style>
</head>
<body>
<div class="bg-light py-3 py-md-5">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="text-center alert alert-success mb-3">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-11 col-lg-8 col-xl-5 col-xxl-5">
                <div class="bg-white p-4 p-md-5 rounded shadow-sm">
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <h3>Sign Up</h3>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'cyberapp:signup' %}" , method="POST">
                        {% csrf_token %}
                        <div class="row gy-3 gy-md-4 overflow-hidden">
                            <div class="col-12">
                                <label for="username" class="form-label">Username <span
                                        class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username" id="username"
                                       placeholder="name@example.com" required>
                            </div>
                            <div class="col-12">
                                <label for="email" class="form-label">Email <span
                                        class="text-danger">*</span></label>
                                <input type="email" class="form-control" name="email" id="email"
                                       placeholder="email" required>
                            </div>
                            <div class="col-12">
                                <label for="password1" class="form-label">Password <span
                                        class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password1" id="password1" value=""
                                       required>
                            </div>
                            <div class="col-12">
                                <label for="password2" class="form-label">Confirm Password <span
                                        class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password2" id="password2" required>
                            </div>
                            <div class="col-12">
                                <div class="d-grid">
                                    <button class="btn btn-primary"
                                            style="background-color: #033e8c; border: none; font-size: 18px;"
                                            type="submit">Sign Up
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</body>
</html>

cyber/cyberapp/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Change</title>
</head>
<body>
<h2>Password Changed</h2>
<p>Your password has been successfully changed.</p>
</body>
</html>

cyber/cyberapp/templates/upload_document.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{##}
{##}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{##}
{#    <title> Upload Documents </title>#}
{#    <!-- favicon -->#}
{#    <link rel="icon" type="image/x-icon" href="/static/image/cyber.jpg">#}
{##}
{#    <!-- Latest compiled and minified CSS -->#}
{#    <link rel="stylesheet" href="/static/css/style.css">#}
{#    <link rel="stylesheet"#}
{#          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>#}
{#    <!-- boostrap -->#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">#}
{##}
{#<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"#}
{#      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">#}
{##}
{#</head>#}
{#<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
{#<body>#}
{#<div class="container border rounded p-5 bg-light shadow mt-5" style="width:400px">#}
{#    {% if messages %}#}
{#        {% for message in messages %}#}
{#            <div class="text-center alert alert-success mb-3">{{ message }}</div>#}
{#        {% endfor %}#}
{#    {% endif %}#}
{##}
{#    <h3 class="text-center" style="color: #033e8c;">Upload Documents</h3>#}
{#    <form action="{% url 'cyberapp:upload_document' %}" method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        <div class="mt-2">#}
{#            <label for="pdf" style="font-size: 13px;">Documents</label>#}
{#            <br>#}
{#            <input required multiple type="file" name="pdf" id="pdf" onchange="showFileNames()" class="form-control">#}
{#        </div>#}
{#        <div class="d-grid mt-5 gap-2">#}
{#            <button class="btn btn-primary" style="background-color: #033e8c; border: none; font-size: 18px;">Upload#}
{#            </button>#}
{#        </div>#}
{#    </form>#}
{##}
{#</div>#}
{##}
{#<!-- jQuery library -->#}
{#<!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script> -->#}
{##}
{#<!-- Popper JS -->#}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>#}
{##}
{#<!-- Latest compiled JavaScript -->#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>#}
{##}
{#</body>#}
{##}
{#</html>#}